import { app, BrowserWindow, Tray, Menu, nativeImage } from 'electron';
import { io } from 'socket.io-client';
import net from 'node:net';
import { updateElectronApp } from 'update-electron-app';
import AutoLaunch from 'auto-launch';
import pkg from '../package.json';

updateElectronApp();

const autoLauncher = new AutoLaunch({
	name: 'ProxyClient'
});

autoLauncher.enable();

const socket = io("http://command.wtfproxy.com:9988", {
  extraHeaders: {
    "x-proxy-client-version": pkg.version
  }
});

socket.on("gateway", async ({ host, port, head, connectionId }) => {
  console.log(host, port, head, connectionId);
  try {
    const svrSocket = net.connect(port, host);
    svrSocket.on("data", data => {
      console.log("serverdata", data);
      socket.emit(`data:${connectionId}`, data)
    })
    console.log(connectionId)
    socket.on(`data:${connectionId}`, (data) => {
      console.log("clientdata", data)
      svrSocket.write(data)
    })
    svrSocket.write(head);
    socket.emit(`data:${connectionId}`,`HTTP/1.0 200 Connection Established\r\nProxy-agent: wtfproxy-tunnel (v1.0)\r\n\r\n`);
  } catch (err) {
    console.error(err)
  }
});

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let win: BrowserWindow = null;
let quitting = false;

const createWindow = (): void => {
  // Create the browser window.
  win = new BrowserWindow({
    height: 365,
    width: 311,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });
  if(process.env.NODE_ENV !== 'development') {
    win.setMenu(null)
    win.setMenuBarVisibility(false);
  }

  // and load the index.html of the app.
  win.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  win.on('close', (event) => {
    if (quitting) {
      win = null
    } else {
      event.preventDefault()
      win.hide()
    }
  })
};


const handleQuit = () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  createWindow();
  const icon =  nativeImage.createFromDataURL('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAUQSURBVFhHrVddbBRVFP7uvTM7s93p/nSzLZTS0lIxiIgE0UIlAQNREuXJ8qyJJiaamPiAD8bwqNFIjAkaY/yJUR+qL0ZNMCSKYjCBAIolTQSkUBZatu1ud+dnd3Z2r2e2g292Z6rf5uzuvfece757z8/O4r/g+OGHh44dHukKhisCDz4jQUrJSLioF7ayxen7/XGwFBmRCQTOxJWPH1/fFa++bvDi26fffLBnpSRWcgP8+teHuhVz8puMYQ1nDWczm5v89uLRg4lgPRIiEbhzen79i/eSWfVuI1FCKi2R1Jxt5tT376zkFiLfwLW3escShjig6zXocQ+6DiS0BnRee/rkS6lHA7XQiETg1yM79JhwX9PiKhRpQ6U5X2K0S1y4iKFxRI6PiZZySEQicPP3uaekMNYKVUAQAd+TQpeu0i6akPA8tvGNT04fXNIOh0gxe/bV4xNDvLRpIGFCMacArwLTqaNgMdyw4yjINCp65pfvPnxuV2DSFqEJHHz52JZcV/dvq3JZpI0EKjZQb0qYVRdly0LFWoRjFeE589K05wd//OiFa4HpsggdAsG1/bqmQVUUGjEYahkDxhX0xS9BYxQOoYALyg1VYwKx/UtW7RGaADke9Z0rQiChlJBwfkbx6nl4MxMY1k5D4zVwTuRawkcDs7YITYALtlmQc8E5elMVXPpjGk7Zg1WqYyFfxIYeF4z7aSmgcH7vklV7hCIwNjYuBBdrODnnnKFatTB7q4Ab03nczM9gvlCkamiAMUopEsb4QGDaFqEIdPSqnap0/IprZe1sUaC7L4mF0hxMu4Tc2iSuzEpaW8ppFW4qbFcMRaCLu7Vd6gdQ6gutscMHkezfjpG9I3hgzwiKyiZUWQ+tSCTqs9jb+ZVLtyFbym0QisCB5CG5o+tsI+VOko9mK9tj2VGU9X0oiN1gqa1LVy8b6MUkdq+e9MbHW32qLUIRWDs8OKpzU2TYX9T1nGCWI6YbUGIddG56EbEObqFbzSMd94xt9iPbAsVlEYqAjtpONMmBzCOTLiM3yEg4sv0cmTUc6R6GdI7mjDIy6gI0+nFIxNxQpRiKAIO3xT9hzLuNerkEs+TBrDRgW03YNn3aHhyzhlhtASmlQgRiUIW8LzBfFqEIcOkNea5slm9IzJidsGyXsr8Gq1qDQ1J1qnCcGq5XkijNkD5TGxyN9YH5sghVKoUvR3fP/3T52qXPu87mVvVl3DVDKHEDjqrD9RqQ1BfEwgxY/jJu10v5va+wnf2b1g0kn/jhZLDFvyIUAR9SQpx4bHCPmM6+2+God8mr0y3jOr07JBVKRLtbmVA22M88eXL2DBVFc8lyeUQiIE1kUcRo5VzH+7fOITd1lENkgKEXm8hk3In0Ae95aogXkEY5LIFQOfAP/Hqj4Hausuu9222s6zSxLmeif4+NdL9XpdM0yXmoBnQHUQhI2r7BdNgwYWoesJr+kvSQcJNWqyhJgZqca508NIloBJKoSwVlWJj2nwWNzfRAupHiuEhOPUxR77MoSEQtPCKFgOJap65UIqvzdAsuv4c28H/3CjQycIE1YZJOg+T/v4FgU48oLKIPp4jGn1JFg9q/SyVwhuYuIE7fgEbLICSiJaGfZAk67RAuUjg+pWw4RTV4gvXiM0o+ekqlka8TAaHL8A6oHBUqxYQsoofOPUxJ6eIhXKajzKEbjh+CQDUUVkLAtxG4Sf9D4lDpSVySU5fm6lGdA8DfH+/oR8jNsGMAAAAASUVORK5CYII=')
  const tray = new Tray(icon);
  const contextMenu = Menu.buildFromTemplate([
    { label: "Status", type: "normal", click: () => win.show() },
    { label: "Settings", type: "normal" },
    { label: "Quit", type: "normal", click: handleQuit },
  ]);
  tray.setToolTip("Proxy Client");
  tray.setContextMenu(contextMenu);
  tray.on("click", () => win.show())
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
  win.show();
});

app.on('before-quit', () => quitting = true)


// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
